/*
    wxWeaver - A GUI Designer Editor for wxWidgets.
    Copyright (C) 2005 José Antonio Hurtado (as wxFormBuilder)
    Copyright (C) 2021 Andrea Zanellato <redtid3@gmail.com>

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/
#include <plugin.h>
#include <ticpp.h>
#include <xrcconv.h>

#include <wx/animate.h>
#include <wx/aui/auibar.h>
#include <wx/bmpcbox.h>
#include <wx/listctrl.h>
#include <wx/statline.h>
#include <wx/infobar.h>

#include <unordered_map>

// Custom status bar class for windows to prevent the status bar gripper from
// moving the entire wxWeaver window
#if defined(__WIN32__) && wxUSE_NATIVE_STATUSBAR
class wxIndependentStatusBar : public wxStatusBar {
public:
    wxIndependentStatusBar(wxWindow* parent, wxWindowID id = wxID_ANY,
                           long style = wxSTB_SIZEGRIP,
                           const wxString& name = wxStatusBarNameStr)
        : wxStatusBar(parent, id, style, name)
    {
    }

    // override this virtual function to prevent the status bar from moving the main frame
    virtual WXLRESULT MSWWindowProc(WXUINT nMsg, WXWPARAM wParam, WXLPARAM lParam)
    {
        return wxStatusBarBase::MSWWindowProc(nMsg, wParam, lParam);
    }
};
#else
typedef wxStatusBar wxIndependentStatusBar;
#endif

class wxLeftDownRedirect : public wxEvtHandler {
public:
    wxLeftDownRedirect(wxWindow* win, IManager* manager)
        : m_window(win)
        , m_manager(manager)
    {
    }

private:
    void OnLeftDown(wxMouseEvent&)
    {
        m_manager->SelectObject(m_window);
    }

    wxWindow* m_window;
    IManager* m_manager;

    wxDECLARE_EVENT_TABLE();
};

BEGIN_EVENT_TABLE(wxLeftDownRedirect, wxEvtHandler)
EVT_LEFT_DOWN(wxLeftDownRedirect::OnLeftDown)
END_EVENT_TABLE()

// Custom Aui toolbar
class AuiToolBar : public wxAuiToolBar {

    friend class AuiToolBarComponent;

public:
    AuiToolBar(wxWindow* win, IManager* manager, wxWindowID id,
               wxPoint pos, wxSize size, long style)
        : wxAuiToolBar(win, id, pos, size, style)
    {
        m_manager = manager;
    }

    void SetObject(int index, wxObject* pObject)
    {
        m_aObjects[index] = pObject;
    }
    wxObject* GetObject(int index)
    {
        return m_aObjects[index];
    }

protected:
    IManager* m_manager;

    wxMenu* GetMenuFromObject(IObject* menu);

    void OnDropDownMenu(wxAuiToolBarEvent& event);
    void OnTool(wxCommandEvent& event);

private:
    std::unordered_map<int, wxObject*> m_aObjects;

    wxDECLARE_EVENT_TABLE();
};

BEGIN_EVENT_TABLE(AuiToolBar, wxAuiToolBar)
EVT_AUITOOLBAR_TOOL_DROPDOWN(wxID_ANY, AuiToolBar::OnDropDownMenu)
EVT_TOOL(wxID_ANY, AuiToolBar::OnTool)
END_EVENT_TABLE()

/**
    Event handler for events generated by controls in this plugin
*/
class ComponentEvtHandler : public wxEvtHandler {
    friend class AuiToolBarComponent;

public:
    ComponentEvtHandler(wxWindow* win, IManager* manager)
        : m_window(win)
        , m_manager(manager)
    {
    }

protected:
    void OnText(wxCommandEvent& event);
    void OnChecked(wxCommandEvent& event);
    void OnChoice(wxCommandEvent& event);
    void OnComboBox(wxCommandEvent& event);
    void OnTool(wxCommandEvent& event);
    void OnButton(wxCommandEvent& event);
    void OnTimer(wxTimerEvent& event);

private:
    wxWindow* m_window;
    IManager* m_manager;
    wxTimer m_timer;

    wxDECLARE_EVENT_TABLE();
};

BEGIN_EVENT_TABLE(ComponentEvtHandler, wxEvtHandler)
EVT_TEXT(wxID_ANY, ComponentEvtHandler::OnText)
EVT_CHECKBOX(wxID_ANY, ComponentEvtHandler::OnChecked)
EVT_CHOICE(wxID_ANY, ComponentEvtHandler::OnChoice)
EVT_COMBOBOX(wxID_ANY, ComponentEvtHandler::OnComboBox)

// Tools do not get click events, so this will help select them
EVT_TOOL(wxID_ANY, ComponentEvtHandler::OnTool)

// wxInfoBar related handlers
EVT_BUTTON(wxID_ANY, ComponentEvtHandler::OnButton)
EVT_TIMER(wxID_ANY, ComponentEvtHandler::OnTimer)
END_EVENT_TABLE()

class ButtonComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxString label = obj->GetPropertyAsString(_("label"));
        wxButton* button = new wxButton(
            (wxWindow*)parent, wxID_ANY,
            label,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        if (obj->GetPropertyAsInteger(_("markup")))
            button->SetLabelMarkup(label);

        if (obj->GetPropertyAsInteger(_("default")))
            button->SetDefault();

        if (obj->GetPropertyAsInteger(_("auth_needed")))
            button->SetAuthNeeded();

        if (!obj->IsNull(_("bitmap")))
            button->SetBitmap(obj->GetPropertyAsBitmap(_("bitmap")));

        if (!obj->IsNull(_("disabled")))
            button->SetBitmapDisabled(obj->GetPropertyAsBitmap(_("disabled")));

        if (!obj->IsNull(_("pressed")))
            button->SetBitmapPressed(obj->GetPropertyAsBitmap(_("pressed")));

        if (!obj->IsNull(_("focus")))
            button->SetBitmapFocus(obj->GetPropertyAsBitmap(_("focus")));

        if (!obj->IsNull(_("current")))
            button->SetBitmapCurrent(obj->GetPropertyAsBitmap(_("current")));

        if (!obj->IsNull(_("position")))
            button->SetBitmapPosition(
                static_cast<wxDirection>(obj->GetPropertyAsInteger(_("position"))));

        if (!obj->IsNull(_("margins")))
            button->SetBitmapMargins(obj->GetPropertyAsSize(_("margins")));

        return button;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxButton"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("default"), _("default"), XRC_TYPE_BOOL);
        xrc.AddProperty(_("auth_needed"), _("auth_needed"), XRC_TYPE_BOOL);
        xrc.AddProperty(_("markup"), _("markup"), XRC_TYPE_BOOL);
        xrc.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);

        if (!obj->IsNull(_("disabled")))
            xrc.AddProperty(_("disabled"), _("disabled"), XRC_TYPE_BITMAP);

        if (!obj->IsNull(_("pressed")))
            xrc.AddProperty(_("pressed"), _("pressed"), XRC_TYPE_BITMAP);

        if (!obj->IsNull(_("focus")))
            xrc.AddProperty(_("focus"), _("focus"), XRC_TYPE_BITMAP);

        if (!obj->IsNull(_("current")))
            xrc.AddProperty(_("current"), _("current"), XRC_TYPE_BITMAP);

        if (!obj->IsNull(_("position")))
            xrc.AddProperty(_("position"), _("position"), XRC_TYPE_TEXT);

        if (!obj->IsNull(_("margins")))
            xrc.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);

        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxButton"));
        filter.AddWindowProperties();
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        filter.AddProperty(_("default"), _("default"), XRC_TYPE_BOOL);
        filter.AddProperty(_("auth_needed"), _("auth_needed"), XRC_TYPE_BOOL);
        filter.AddProperty(_("markup"), _("markup"), XRC_TYPE_BOOL);
        filter.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("disabled"), _("disabled"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("pressed"), _("pressed"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("focus"), _("focus"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("current"), _("current"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("position"), _("position"), XRC_TYPE_TEXT);
        filter.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        return filter.GetXfbObject();
    }
};

class BitmapButtonComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxBitmapButton* bmpButton = new wxBitmapButton(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsBitmap(_("bitmap")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        // To stay in sync what the generator templates do apply the markup label here as well
        if (obj->GetPropertyAsInteger(_("markup")))
            bmpButton->SetLabelMarkup(obj->GetPropertyAsString(_("label")));

        if (obj->GetPropertyAsInteger(_("default")))
            bmpButton->SetDefault();

        if (obj->GetPropertyAsInteger(_("auth_needed")))
            bmpButton->SetAuthNeeded();

        if (!obj->IsNull(_("disabled")))
            bmpButton->SetBitmapDisabled(obj->GetPropertyAsBitmap(_("disabled")));

        if (!obj->IsNull(_("pressed")))
            bmpButton->SetBitmapPressed(obj->GetPropertyAsBitmap(_("pressed")));

        if (!obj->IsNull(_("focus")))
            bmpButton->SetBitmapFocus(obj->GetPropertyAsBitmap(_("focus")));

        if (!obj->IsNull(_("current")))
            bmpButton->SetBitmapCurrent(obj->GetPropertyAsBitmap(_("current")));

        if (!obj->IsNull(_("position")))
            bmpButton->SetBitmapPosition(
                static_cast<wxDirection>(obj->GetPropertyAsInteger(_("position"))));

        if (!obj->IsNull(_("margins")))
            bmpButton->SetBitmapMargins(obj->GetPropertyAsSize(_("margins")));

        return bmpButton;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxBitmapButton"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);
        if (!obj->IsNull(_("disabled"))) {
            xrc.AddProperty(_("disabled"), _("disabled"), XRC_TYPE_BITMAP);
        }
        if (!obj->IsNull(_("pressed"))) {
            xrc.AddProperty(_("pressed"), _("pressed"), XRC_TYPE_BITMAP);
        }
        if (!obj->IsNull(_("focus"))) {
            xrc.AddProperty(_("focus"), _("focus"), XRC_TYPE_BITMAP);
        }
        if (!obj->IsNull(_("current"))) {
            xrc.AddProperty(_("current"), _("current"), XRC_TYPE_BITMAP);
        }
        if (!obj->IsNull(_("position"))) {
            xrc.AddProperty(_("position"), _("position"), XRC_TYPE_TEXT);
        }
        if (!obj->IsNull(_("margins"))) {
            xrc.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        }
        xrc.AddProperty(_("default"), _("default"), XRC_TYPE_BOOL);
        xrc.AddProperty(_("auth_needed"), _("auth_needed"), XRC_TYPE_BOOL);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxBitmapButton"));
        filter.AddWindowProperties();
        filter.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("disabled"), _("disabled"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("pressed"), _("pressed"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("focus"), _("focus"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("current"), _("current"), XRC_TYPE_BITMAP);
        filter.AddProperty(_("position"), _("position"), XRC_TYPE_TEXT);
        filter.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        filter.AddProperty(_("default"), _("default"), XRC_TYPE_BOOL);
        filter.AddProperty(_("auth_needed"), _("auth_needed"), XRC_TYPE_BOOL);
        return filter.GetXfbObject();
    }
};

class TextCtrlComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxTextCtrl* textCtrl = new wxTextCtrl(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsString(_("value")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        if (!obj->IsNull(_("maxlength")))
            textCtrl->SetMaxLength(obj->GetPropertyAsInteger(_("maxlength")));

        textCtrl->PushEventHandler(new ComponentEvtHandler(textCtrl, GetManager()));
        return textCtrl;
    }

    void Cleanup(wxObject* obj) override
    {
        wxTextCtrl* textCtrl = wxDynamicCast(obj, wxTextCtrl);
        if (textCtrl)
            textCtrl->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxTextCtrl"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("value"), _("value"), XRC_TYPE_TEXT);
        if (!obj->IsNull(_("maxlength")))
            xrc.AddProperty(_("maxlength"), _("maxlength"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxTextCtrl"));
        filter.AddWindowProperties();
        filter.AddProperty(_("value"), _("value"), XRC_TYPE_TEXT);
        filter.AddProperty(_("maxlength"), _("maxlength"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};
// TODO
void ComponentEvtHandler::OnText(wxCommandEvent&)
{
    wxTextCtrl* textCtrl = wxDynamicCast(m_window, wxTextCtrl);
    if (textCtrl) {
        m_manager->ModifyProperty(m_window, _("value"), textCtrl->GetValue());
        textCtrl->SetInsertionPointEnd();
        textCtrl->SetFocus();
        return;
    }

    wxComboBox* comboBox = wxDynamicCast(m_window, wxComboBox);
    if (comboBox) {
        m_manager->ModifyProperty(m_window, _("value"), comboBox->GetValue());
        comboBox->SetInsertionPointEnd();
        comboBox->SetFocus();
        return;
    }
}

class StaticTextComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxString label = obj->GetPropertyAsString(_("label"));
        wxStaticText* staticText = new wxStaticText(
            (wxWindow*)parent, wxID_ANY, label,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        staticText->Wrap(obj->GetPropertyAsInteger(_("wrap")));

        if (obj->GetPropertyAsInteger(_("markup")))
            staticText->SetLabelMarkup(label);

        return staticText;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        wxString name = obj->GetPropertyAsString(_("name"));
        ObjectToXrcFilter xrc(obj, _("wxStaticText"), name);
        xrc.AddWindowProperties();
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("wrap"), _("wrap"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxStaticText"));
        filter.AddWindowProperties();
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        filter.AddProperty(_("wrap"), _("wrap"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};

class ComboBoxComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxComboBox* comboBox = new wxComboBox(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsString(_("value")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")), 0, NULL,
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        // choices
        wxArrayString choices = obj->GetPropertyAsArrayString(_("choices"));
        for (unsigned int i = 0; i < choices.GetCount(); i++)
            comboBox->Append(choices[i]);

        int sel = obj->GetPropertyAsInteger(_("selection"));
        if (sel > wxNOT_FOUND && sel < (int)choices.GetCount())
            comboBox->SetSelection(sel);

        comboBox->PushEventHandler(new ComponentEvtHandler(comboBox, GetManager()));
        return comboBox;
    }

    void Cleanup(wxObject* obj) override
    {
        wxComboBox* comboBox = wxDynamicCast(obj, wxComboBox);
        if (comboBox)
            comboBox->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxComboBox"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("value"), _("value"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("choices"), _("content"), XRC_TYPE_STRINGLIST);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxComboBox"));
        filter.AddWindowProperties();
        filter.AddProperty(_("value"), _("value"), XRC_TYPE_TEXT);
        filter.AddProperty(_("content"), _("choices"), XRC_TYPE_STRINGLIST);
        return filter.GetXfbObject();
    }
};

class BitmapComboBoxComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxBitmapComboBox* bmpComboBox = new wxBitmapComboBox(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsString(_("value")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")), 0, NULL,
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        // choices
        wxArrayString choices = obj->GetPropertyAsArrayString(_("choices"));
        for (unsigned int i = 0; i < choices.GetCount(); i++) {
            wxImage img(choices[i].BeforeFirst(wxChar(58)));
            bmpComboBox->Append(choices[i].AfterFirst(wxChar(58)), wxBitmap(img));
        }
        int sel = obj->GetPropertyAsInteger(_("selection"));
        if (sel > wxNOT_FOUND && sel < (int)choices.GetCount())
            bmpComboBox->SetSelection(sel);

        bmpComboBox->PushEventHandler(new ComponentEvtHandler(bmpComboBox, GetManager()));
        return bmpComboBox;
    }

    void Cleanup(wxObject* obj) override
    {
        wxBitmapComboBox* bmpComboBox = wxDynamicCast(obj, wxBitmapComboBox);
        if (bmpComboBox)
            bmpComboBox->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxBitmapComboBox"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("value"), _("value"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("choices"), _("content"), XRC_TYPE_STRINGLIST);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxBitmapComboBox"));
        filter.AddWindowProperties();
        filter.AddProperty(_("value"), _("value"), XRC_TYPE_TEXT);
        filter.AddProperty(_("content"), _("choices"), XRC_TYPE_STRINGLIST);
        return filter.GetXfbObject();
    }
};

class CheckBoxComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxCheckBox* checkBox = new wxCheckBox(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsString(_("label")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("window_style"))
                | obj->GetPropertyAsInteger(_T("style")));

        checkBox->SetValue(obj->GetPropertyAsInteger(_T("checked")));
        checkBox->PushEventHandler(new ComponentEvtHandler(checkBox, GetManager()));
        return checkBox;
    }

    void Cleanup(wxObject* obj) override
    {
        wxCheckBox* checkBox = wxDynamicCast(obj, wxCheckBox);
        if (checkBox)
            checkBox->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxCheckBox"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("checked"), _("checked"), XRC_TYPE_BOOL);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxCheckBox"));
        filter.AddWindowProperties();
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        filter.AddProperty(_("checked"), _("checked"), XRC_TYPE_BOOL);
        return filter.GetXfbObject();
    }
};

void ComponentEvtHandler::OnChecked(wxCommandEvent&)
{
    wxCheckBox* checkBox = wxDynamicCast(m_window, wxCheckBox);
    if (!checkBox)
        return;

    wxString cbValue;
    cbValue.Printf(wxT("%i"), checkBox->GetValue());
    m_manager->ModifyProperty(m_window, _("checked"), cbValue);
    checkBox->SetFocus();
}

class StaticBitmapComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        return new wxStaticBitmap(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsBitmap(_("bitmap")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("window_style")));
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxStaticBitmap"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxStaticBitmap"));
        filter.AddWindowProperties();
        filter.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);
        return filter.GetXfbObject();
    }
};

// TODO: Remove?
class XpmStaticBitmapComponent : public StaticBitmapComponent {
};

class StaticLineComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        return new wxStaticLine(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxStaticLine"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxStaticLine"));
        filter.AddWindowProperties();
        return filter.GetXfbObject();
    }
};

class ListCtrlComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxListCtrl* listCtrl = new wxListCtrl(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            (obj->GetPropertyAsInteger(_("style"))
             | obj->GetPropertyAsInteger(_("window_style")))
                & ~wxLC_VIRTUAL);

        // Refilling
        int i, j;
        wxString buf;
        if ((listCtrl->GetWindowStyle() & wxLC_REPORT)) {
            for (i = 0; i < 4; i++) {
                buf.Printf(wxT("Label %d"), i);
                listCtrl->InsertColumn(i, buf, wxLIST_FORMAT_LEFT, 80);
            }
        }
        for (j = 0; j < 10; j++) {
            long temp;
            buf.Printf(wxT("Cell (0,%d)"), j);
            temp = listCtrl->InsertItem(j, buf);
            if ((listCtrl->GetWindowStyle() & wxLC_REPORT)) {
                for (i = 1; i < 4; i++) {
                    buf.Printf(wxT("Cell (%d,%d)"), i, j);
                    listCtrl->SetItem(temp, i, buf);
                }
            }
        }
        return listCtrl;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxListCtrl"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxListCtrl"));
        filter.AddWindowProperties();
        return filter.GetXfbObject();
    }
};

class ListBoxComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxListBox* listBox = new wxListBox(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")), 0, NULL,
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        // choices
        wxArrayString choices = obj->GetPropertyAsArrayString(_("choices"));
        for (size_t i = 0; i < choices.Count(); i++)
            listBox->Append(choices[i]);

        return listBox;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxListBox"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("choices"), _("content"), XRC_TYPE_STRINGLIST);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxListBox"));
        filter.AddWindowProperties();
        filter.AddProperty(_("content"), _("choices"), XRC_TYPE_STRINGLIST);
        return filter.GetXfbObject();
    }
};

class RadioBoxComponent : public ComponentBase, public wxEvtHandler {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxArrayString choices = obj->GetPropertyAsArrayString(_("choices"));
        int count = choices.Count();
        if (!count) {
            choices.Add(_("wxRadioBox must have at least one choice"));
            count = 1;
        }

        int majorDim = obj->GetPropertyAsInteger(_("majorDimension"));
        if (majorDim < 1) {
            wxLogWarning(_("majorDimension must be greater than zero."));
            majorDim = 1;
        }

        wxRadioBox* radioBox = new wxRadioBox(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsString(_("label")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            choices, majorDim,
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        int selection = obj->GetPropertyAsInteger(_("selection"));
        if (selection < count)
            radioBox->SetSelection(selection);

        radioBox->Connect(wxEVT_COMMAND_RADIOBOX_SELECTED,
                          wxCommandEventHandler(RadioBoxComponent::OnRadioBox),
                          NULL, this);
        return radioBox;
    }

    void OnRadioBox(wxCommandEvent& event)
    {
        wxRadioBox* radioBox = dynamic_cast<wxRadioBox*>(event.GetEventObject());
        if (!radioBox)
            return;

        wxString value;
        value.Printf(wxT("%i"), radioBox->GetSelection());
        GetManager()->ModifyProperty(radioBox, _("selection"), value);
        radioBox->SetFocus();
        GetManager()->SelectObject(radioBox);
    }

    void Cleanup(wxObject* obj) override
    {
        wxRadioBox* radioBox = dynamic_cast<wxRadioBox*>(obj);
        if (!radioBox)
            return;

        radioBox->Disconnect(
            wxEVT_COMMAND_RADIOBOX_SELECTED,
            wxCommandEventHandler(RadioBoxComponent::OnRadioBox),
            NULL, this);

        ComponentBase::Cleanup(obj);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxRadioBox"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("selection"), _("selection"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("choices"), _("content"), XRC_TYPE_STRINGLIST);
        xrc.AddProperty(_("majorDimension"), _("dimension"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxRadioBox"));
        filter.AddWindowProperties();
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        filter.AddProperty(_("selection"), _("selection"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("content"), _("choices"), XRC_TYPE_STRINGLIST);
        filter.AddProperty(_("dimension"), _("majorDimension"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};

class RadioButtonComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxRadioButton* radioButton = new wxRadioButton(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsString(_("label")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        radioButton->SetValue((obj->GetPropertyAsInteger(_("value"))));
        return radioButton;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxRadioButton"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("value"), _("value"), XRC_TYPE_BOOL);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxRadioButton"));
        filter.AddWindowProperties();
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        filter.AddProperty(_("value"), _("value"), XRC_TYPE_BOOL);
        return filter.GetXfbObject();
    }
};

class StatusBarComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxStatusBar* statusBar = new wxIndependentStatusBar(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        statusBar->SetFieldsCount(obj->GetPropertyAsInteger(_("fields")));
#ifndef __WXMSW__
        statusBar->PushEventHandler(new wxLeftDownRedirect(statusBar, GetManager()));
#endif
        return statusBar;
    }
#ifndef __WXMSW__
    void Cleanup(wxObject* obj) override
    {
        wxStatusBar* statusBar = wxDynamicCast(obj, wxStatusBar);
        if (statusBar)
            statusBar->PopEventHandler(true);
    }
#endif
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxStatusBar"), obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("fields"), _("fields"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxStatusBar"));
        filter.AddWindowProperties();
        filter.AddProperty(_("fields"), _("fields"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};

class MenuBarComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* /*parent*/) override
    {
        return new wxMenuBar(
            obj->GetPropertyAsInteger(_("style"))
            | obj->GetPropertyAsInteger(_("window_style")));
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxMenuBar"), obj->GetPropertyAsString(_("name")));
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxMenuBar"));
        return filter.GetXfbObject();
    }
};

class MenuComponent : public ComponentBase {
public:
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxMenu"), obj->GetPropertyAsString(_("name")));
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxMenu"));
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        return filter.GetXfbObject();
    }
};

class SubMenuComponent : public ComponentBase {
public:
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxMenu"), obj->GetPropertyAsString(_("name")));
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("submenu"));
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        return filter.GetXfbObject();
    }
};

class MenuItemComponent : public ComponentBase {
public:
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxMenuItem"),
                              obj->GetPropertyAsString(_("name")));

        wxString shortcut = obj->GetPropertyAsString(_("shortcut"));
        wxString label;

        if (shortcut.IsEmpty())
            label = obj->GetPropertyAsString(_("label"));
        else
            label = obj->GetPropertyAsString(_("label")) + wxT("\t") + shortcut;

        xrc.AddPropertyValue(_("label"), label, true);
        xrc.AddProperty(_("help"), _("help"), XRC_TYPE_TEXT);

        if (!obj->IsNull(_("bitmap")))
            xrc.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);

        int kind = obj->GetPropertyAsInteger(_("kind"));

        if (obj->GetPropertyAsInteger(_("checked")) && (kind == wxITEM_RADIO || kind == wxITEM_CHECK)) {
            xrc.AddProperty(_("checked"), _("checked"), XRC_TYPE_BOOL);
        }
        if (obj->GetPropertyAsInteger(_("enabled")) == 0)
            xrc.AddProperty(_("enabled"), _("enabled"), XRC_TYPE_BOOL);

        switch (kind) {
        case wxITEM_CHECK:
            xrc.AddPropertyValue(_("checkable"), _("1"));
            break;
        case wxITEM_RADIO:
            xrc.AddPropertyValue(_("radio"), _("1"));
            break;
        }
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxMenuItem"));

        try {
            ticpp::Element* labelElement = xrcObj->FirstChildElement("label");
            wxString label(labelElement->GetText().c_str(), wxConvUTF8);

            wxString shortcut;
            int pos = label.Find(wxT("\\t"));
            if (pos >= 0) {
                shortcut = label.Mid(pos + 2);
                label = label.Left(pos);
            }
            filter.AddPropertyValue(_("label"), label, true);
            filter.AddPropertyValue(_("shortcut"), shortcut);
        } catch (ticpp::Exception&) {
        }
        filter.AddProperty(_("help"), _("help"), XRC_TYPE_TEXT);
        filter.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);
        return filter.GetXfbObject();
    }
};

class SeparatorComponent : public ComponentBase {
public:
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("separator"));
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("separator"));
        return filter.GetXfbObject();
    }
};

class ToolBarComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxToolBar* toolBar = new wxToolBar(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style"))
                | wxTB_NOALIGN | wxTB_NODIVIDER | wxNO_BORDER);

        if (!obj->IsNull(_("bitmapsize")))
            toolBar->SetToolBitmapSize(obj->GetPropertyAsSize(_("bitmapsize")));

        if (!obj->IsNull(_("margins"))) {
            wxSize margins(obj->GetPropertyAsSize(_("margins")));
            toolBar->SetMargins(margins.GetWidth(), margins.GetHeight());
        }
        if (!obj->IsNull(_("packing")))
            toolBar->SetToolPacking(obj->GetPropertyAsInteger(_("packing")));

        if (!obj->IsNull(_("separation")))
            toolBar->SetToolSeparation(obj->GetPropertyAsInteger(_("separation")));

        toolBar->PushEventHandler(new ComponentEvtHandler(toolBar, GetManager()));
        return toolBar;
    }

    void Cleanup(wxObject* obj) override
    {
        wxToolBar* toolBar = wxDynamicCast(obj, wxToolBar);
        if (toolBar)
            toolBar->PopEventHandler(true);
    }

    void OnCreated(wxObject* wxobject, wxWindow* /*wxparent*/) override
    {
        wxToolBar* toolBar = wxDynamicCast(wxobject, wxToolBar);
        if (!toolBar)
            return;

        size_t count = GetManager()->GetChildCount(wxobject);
        for (size_t i = 0; i < count; ++i) {
            wxObject* child = GetManager()->GetChild(wxobject, i);
            IObject* childObj = GetManager()->GetIObject(child);

            if (childObj->GetClassName() == "tool") {
                toolBar->AddTool(
                    wxID_ANY,
                    childObj->GetPropertyAsString(_("label")),
                    childObj->GetPropertyAsBitmap(_("bitmap")),
                    wxNullBitmap,
                    (wxItemKind)childObj->GetPropertyAsInteger(_("kind")),
                    childObj->GetPropertyAsString(_("help")),
                    wxEmptyString, child);
            } else if (childObj->GetClassName() == "toolSeparator") {
                toolBar->AddSeparator();
            } else {
                wxControl* control = wxDynamicCast(child, wxControl);
                if (control)
                    toolBar->AddControl(control);
            }
        }
        toolBar->Realize();
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxToolBar"), obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("bitmapsize"), _("bitmapsize"), XRC_TYPE_SIZE);
        xrc.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        xrc.AddProperty(_("packing"), _("packing"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("separation"), _("separation"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxToolBar"));
        filter.AddWindowProperties();
        filter.AddProperty(_("bitmapsize"), _("bitmapsize"), XRC_TYPE_SIZE);
        filter.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        filter.AddProperty(_("packing"), _("packing"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("separation"), _("separation"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};

wxMenu* AuiToolBar::GetMenuFromObject(IObject* menuObj)
{
    int lastMenuId = wxID_HIGHEST + 1;
    wxMenu* menu = new wxMenu();
    for (unsigned int j = 0; j < menuObj->GetChildCount(); j++) {
        IObject* menuItem = menuObj->GetChildPtr(j);
        if (menuItem->GetObjectTypeName() == wxT("submenu")) {
            menu->Append(
                lastMenuId++,
                menuItem->GetPropertyAsString(wxT("label")),
                GetMenuFromObject(menuItem));
        } else if (menuItem->GetClassName() == wxT("separator")) {
            menu->AppendSeparator();
        } else {
            wxString label = menuItem->GetPropertyAsString(wxT("label"));
            wxString shortcut = menuItem->GetPropertyAsString(wxT("shortcut"));
            if (!shortcut.IsEmpty()) {
                label = label + wxChar('\t') + shortcut;
            }
            wxMenuItem* item = new wxMenuItem(
                menu, lastMenuId++, label,
                menuItem->GetPropertyAsString(wxT("help")),
                (wxItemKind)menuItem->GetPropertyAsInteger(wxT("kind")));

            if (!menuItem->IsNull(wxT("bitmap"))) {
                wxBitmap unchecked = wxNullBitmap;
                if (!menuItem->IsNull(wxT("unchecked_bitmap")))
                    unchecked = menuItem->GetPropertyAsBitmap(wxT("unchecked_bitmap"));
#ifdef __WXMSW__
                item->SetBitmaps(menuItem->GetPropertyAsBitmap(wxT("bitmap")), unchecked);
#elif defined(__WXGTK__)
                item->SetBitmap(menuItem->GetPropertyAsBitmap(wxT("bitmap")));
#endif
            } else {
                if (!menuItem->IsNull(wxT("unchecked_bitmap"))) {
#ifdef __WXMSW__
                    item->SetBitmaps(wxNullBitmap, menuItem->GetPropertyAsBitmap(wxT("unchecked_bitmap")));
#endif
                }
            }
            menu->Append(item);

            if (item->GetKind() == wxITEM_CHECK
                && menuItem->GetPropertyAsInteger(wxT("checked"))) {
                item->Check(true);
            }
            item->Enable((menuItem->GetPropertyAsInteger(wxT("enabled"))));
        }
    }
    return menu;
}

void AuiToolBar::OnDropDownMenu(wxAuiToolBarEvent& event)
{
    wxAuiToolBar* auiToolBar = wxDynamicCast(event.GetEventObject(), wxAuiToolBar);
    if (!auiToolBar)
        return;

    wxAuiToolBarItem* item = auiToolBar->FindTool(event.GetId());
    if (!item)
        return;

    if (item->HasDropDown()) {
        wxObject* wxobject = GetObject(item->GetUserData());

        if (wxobject)
            m_manager->SelectObject(wxobject);

        auiToolBar->SetToolSticky(item->GetId(), true);
        wxRect rect = auiToolBar->GetToolRect(item->GetId());
        wxPoint pt = auiToolBar->ClientToScreen(rect.GetBottomLeft());
        pt = auiToolBar->ScreenToClient(pt);

        wxObject* child = m_manager->GetChild(wxobject, 0);
        if (!child)
            return;

        auiToolBar->PopupMenu(GetMenuFromObject(m_manager->GetIObject(child)), pt);
        auiToolBar->SetToolSticky(item->GetId(), false);
        /*
        TODO: For some unknown reason, this event is occasionally
        propagated upwards even though it's been handled here and there's
        a clash of IDs between that given a tool by wxAui and the IDs in mainframe.cpp
        which sometimes results in a wxWeaver dialog being fired.
        So StopPropagation() now, but those IDs need changing to avoid clashes.
        event.StopPropagation();
        */
    }
}

void AuiToolBar::OnTool(wxCommandEvent& event)
{
    AuiToolBar* auiToolBar = wxDynamicCast(event.GetEventObject(), AuiToolBar);
    if (!auiToolBar)
        return;

    wxAuiToolBarItem* item = auiToolBar->FindTool(event.GetId());
    if (item) {
        wxObject* wxobject = GetObject(item->GetUserData());
        if (wxobject)
            m_manager->SelectObject(wxobject);
    }
}

class AuiToolBarComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        AuiToolBar* auiToolBar = new AuiToolBar(
            (wxWindow*)parent, GetManager(), wxID_ANY,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style")));
#if 0
                | obj->GetPropertyAsInteger(_("window_style"))
                | wxTB_NOALIGN | wxTB_NODIVIDER | wxNO_BORDER);
#endif
        if (!obj->IsNull(_("bitmapsize")))
            auiToolBar->SetToolBitmapSize(obj->GetPropertyAsSize(_("bitmapsize")));

        if (!obj->IsNull(_("margins"))) {
            wxSize margins(obj->GetPropertyAsSize(_("margins")));
            auiToolBar->SetMargins(margins.GetWidth(), margins.GetHeight());
        }
        if (!obj->IsNull(_("packing")))
            auiToolBar->SetToolPacking(obj->GetPropertyAsInteger(_("packing")));

        if (!obj->IsNull(_("separation")))
            auiToolBar->SetToolSeparation(obj->GetPropertyAsInteger(_("separation")));

        return auiToolBar;
    }

    void OnCreated(wxObject* wxobject, wxWindow* /*wxparent*/) override
    {
        AuiToolBar* auiToolBar = wxDynamicCast(wxobject, AuiToolBar);
        if (!auiToolBar)
            return;

        size_t count = GetManager()->GetChildCount(wxobject);
        for (size_t i = 0; i < count; ++i) {
            wxObject* child = GetManager()->GetChild(wxobject, i);
            IObject* childObj = GetManager()->GetIObject(child);
            if (wxT("tool") == childObj->GetClassName()) {
                auiToolBar->AddTool(
                    wxID_ANY,
                    childObj->GetPropertyAsString(_("label")),
                    childObj->GetPropertyAsBitmap(_("bitmap")),
                    wxNullBitmap,
                    (wxItemKind)childObj->GetPropertyAsInteger(_("kind")),
                    childObj->GetPropertyAsString(_("help")),
                    wxEmptyString, child);

                wxAuiToolBarItem* itm = auiToolBar->FindToolByIndex(i);
                wxASSERT(itm);
                itm->SetUserData(i);
                auiToolBar->SetObject(i, child);
                if (childObj->GetPropertyAsInteger(_("context_menu")) == 1
                    && !itm->HasDropDown())
                    auiToolBar->SetToolDropDown(itm->GetId(), true);
                else if (childObj->GetPropertyAsInteger(_("context_menu")) == 0
                         && itm->HasDropDown())
                    auiToolBar->SetToolDropDown(itm->GetId(), false);
            } else if (wxT("toolSeparator") == childObj->GetClassName()) {
                auiToolBar->AddSeparator();
            } else {
                wxControl* control = wxDynamicCast(child, wxControl);
                if (control)
                    auiToolBar->AddControl(control);
            }
        }
        auiToolBar->Realize();
    }
#if 0
    ticpp::Element* ExportToXrc(IObject *obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxAuiToolBar"), obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("bitmapsize"), _("bitmapsize"), XRC_TYPE_SIZE);
        xrc.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        xrc.AddProperty(_("packing"), _("packing"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("separation"), _("separation"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc( ticpp::Element* xrcObj )
    {
        XrcToXfbFilter filter(xrcObj, _("wxAuiToolBar"));
        filter.AddWindowProperties();
        filter.AddProperty(_("bitmapsize"), _("bitmapsize"), XRC_TYPE_SIZE);
        filter.AddProperty(_("margins"), _("margins"), XRC_TYPE_SIZE);
        filter.AddProperty(_("packing"), _("packing"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("separation"), _("separation"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
#endif
};

void ComponentEvtHandler::OnTool(wxCommandEvent& event)
{
    //FIXME: Same as above
    wxToolBar* toolBar = wxDynamicCast(event.GetEventObject(), wxToolBar);
    if (!toolBar)
        return;

    wxObject* wxobject = toolBar->GetToolClientData(event.GetId());
    if (wxobject)
        m_manager->SelectObject(wxobject);
}

class ToolComponent : public ComponentBase {
public:
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("tool"), obj->GetPropertyAsString(_("name")));
        xrc.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("tooltip"), _("tooltip"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("statusbar"), _("longhelp"), XRC_TYPE_TEXT);
        xrc.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);

        wxItemKind kind = (wxItemKind)obj->GetPropertyAsInteger(_("kind"));
        if (wxITEM_CHECK == kind) {
            xrc.AddPropertyValue(wxT("toggle"), wxT("1"));
        } else if (wxITEM_RADIO == kind) {
            xrc.AddPropertyValue(wxT("radio"), wxT("1"));
        }
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("tool"));
        filter.AddProperty(_("longhelp"), _("statusbar"), XRC_TYPE_TEXT);
        filter.AddProperty(_("tooltip"), _("tooltip"), XRC_TYPE_TEXT);
        filter.AddProperty(_("label"), _("label"), XRC_TYPE_TEXT);
        filter.AddProperty(_("bitmap"), _("bitmap"), XRC_TYPE_BITMAP);

        bool gotToggle = false;
        bool gotRadio = false;
        ticpp::Element* toggle = xrcObj->FirstChildElement("toggle", false);
        if (toggle) {
            toggle->GetTextOrDefault(&gotToggle, false);
            if (gotToggle)
                filter.AddPropertyValue(_("kind"), wxT("wxITEM_CHECK"));
        }
        if (!gotToggle) {
            ticpp::Element* radio = xrcObj->FirstChildElement("radio", false);
            if (radio) {
                radio->GetTextOrDefault(&gotRadio, false);
                if (gotRadio)
                    filter.AddPropertyValue(_("kind"), wxT("wxITEM_RADIO"));
            }
        }
        if (!(gotToggle || gotRadio))
            filter.AddPropertyValue(_("kind"), wxT("wxITEM_NORMAL"));

        return filter.GetXfbObject();
    }
};

class ToolSeparatorComponent : public ComponentBase {
public:
    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("separator"));
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("toolSeparator"));
        return filter.GetXfbObject();
    }
};

class ChoiceComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxArrayString choices = obj->GetPropertyAsArrayString(_("choices"));

        // TODO: is "new" necessary?
        wxString* strings = new wxString[choices.GetCount()];
        for (unsigned int i = 0; i < choices.GetCount(); i++)
            strings[i] = choices[i];

        wxChoice* choice = new wxChoice(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            (int)choices.Count(), strings,
            obj->GetPropertyAsInteger(_("window_style")));

        int sel = obj->GetPropertyAsInteger(_("selection"));
        if (sel < (int)choices.GetCount())
            choice->SetSelection(sel);

        delete[] strings;

        choice->PushEventHandler(new ComponentEvtHandler(choice, GetManager()));
        return choice;
    }

    void Cleanup(wxObject* obj) override
    {
        wxChoice* choice = wxDynamicCast(obj, wxChoice);
        if (choice)
            choice->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxChoice"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("selection"), _("selection"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("choices"), _("content"), XRC_TYPE_STRINGLIST);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxChoice"));
        filter.AddWindowProperties();
        filter.AddProperty(_("selection"), _("selection"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("content"), _("choices"), XRC_TYPE_STRINGLIST);
        return filter.GetXfbObject();
    }
};

void ComponentEvtHandler::OnChoice(wxCommandEvent&)
{
    wxChoice* choice = wxDynamicCast(m_window, wxChoice);
    if (!choice)
        return;

    wxString value;
    value.Printf(wxT("%i"), choice->GetSelection());
    m_manager->ModifyProperty(m_window, _("selection"), value);
    choice->SetFocus();
}

void ComponentEvtHandler::OnComboBox(wxCommandEvent&)
{
    wxComboBox* comboBox = wxDynamicCast(m_window, wxComboBox);
    if (!comboBox)
        return;

    wxString value;
    value.Printf(wxT("%i"), comboBox->GetSelection());
    m_manager->ModifyProperty(m_window, _("selection"), value);
    comboBox->SetFocus();
}

class SliderComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        return new wxSlider(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsInteger(_("value")),
            obj->GetPropertyAsInteger(_("minValue")),
            obj->GetPropertyAsInteger(_("maxValue")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style"))
                | obj->GetPropertyAsInteger(_("window_style")));
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxSlider"), obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("value"), _("value"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("minValue"), _("min"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("maxValue"), _("max"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxSlider"));
        filter.AddWindowProperties();
        filter.AddProperty(_("value"), _("value"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("min"), _("minValue"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("max"), _("maxValue"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};

class GaugeComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxGauge* gauge = new wxGauge(
            (wxWindow*)parent, wxID_ANY,
            obj->GetPropertyAsInteger(_("range")),
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        gauge->SetValue(obj->GetPropertyAsInteger(_("value")));
        return gauge;
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxGauge"), obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("range"), _("range"), XRC_TYPE_INTEGER);
        xrc.AddProperty(_("value"), _("value"), XRC_TYPE_INTEGER);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxGauge"));
        filter.AddWindowProperties();
        filter.AddProperty(_("range"), _("range"), XRC_TYPE_INTEGER);
        filter.AddProperty(_("value"), _("value"), XRC_TYPE_INTEGER);
        return filter.GetXfbObject();
    }
};

class AnimCtrlComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxAnimationCtrl* animationCtrl = new wxAnimationCtrl(
            (wxWindow*)parent, wxID_ANY,
            wxNullAnimation,
            obj->GetPropertyAsPoint(_("pos")),
            obj->GetPropertyAsSize(_("size")),
            obj->GetPropertyAsInteger(_("style"))
                | obj->GetPropertyAsInteger(_("window_style")));

        if (!obj->IsNull(_("animation"))) {
            if (animationCtrl->LoadFile(obj->GetPropertyAsString(_("animation")))) {
                if (!obj->IsNull(_("play"))
                    && (obj->GetPropertyAsInteger(_("play")) == 1))
                    animationCtrl->Play();
                else
                    animationCtrl->Stop();
            }
        }
        if (!obj->IsNull(_("inactive_bitmap"))) {
            wxBitmap bmp = obj->GetPropertyAsBitmap(_("inactive_bitmap"));
            if (bmp.IsOk())
                animationCtrl->SetInactiveBitmap(bmp);
            else
                animationCtrl->SetInactiveBitmap(wxNullBitmap);
        }
        animationCtrl->PushEventHandler(new ComponentEvtHandler(animationCtrl, GetManager()));
        return animationCtrl;
    }

    void Cleanup(wxObject* obj) override
    {
        wxAnimationCtrl* animationCtrl = wxDynamicCast(obj, wxAnimationCtrl);
        if (animationCtrl)
            animationCtrl->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
        ObjectToXrcFilter xrc(obj, _("wxAnimationCtrl"),
                              obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
        xrc.AddProperty(_("animation"), _("animation"), XRC_TYPE_TEXT);
        return xrc.GetXrcObject();
    }

    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxAnimationCtrl"));
        filter.AddWindowProperties();
        filter.AddProperty(_("animation"), _("animation"), XRC_TYPE_TEXT);
        return filter.GetXfbObject();
    }
};

class InfoBarComponent : public ComponentBase {
public:
    wxObject* Create(IObject* obj, wxObject* parent) override
    {
        wxInfoBar* infoBar = new wxInfoBar((wxWindow*)parent);

        infoBar->SetShowHideEffects(
            (wxShowEffect)obj->GetPropertyAsInteger(_("show_effect")),
            (wxShowEffect)obj->GetPropertyAsInteger(_("hide_effect")));

        infoBar->SetEffectDuration(obj->GetPropertyAsInteger(_("duration")));
        infoBar->ShowMessage(wxT("Message ..."), wxICON_INFORMATION);
        infoBar->PushEventHandler(new ComponentEvtHandler(infoBar, GetManager()));
        return infoBar;
    }

    void Cleanup(wxObject* obj) override
    {
        wxInfoBar* infoBar = wxDynamicCast(obj, wxInfoBar);
        if (infoBar)
            infoBar->PopEventHandler(true);
    }

    ticpp::Element* ExportToXrc(IObject* obj) override
    {
#if wxVERSION_NUMBER >= 3130
        ObjectToXrcFilter xrc(obj, _("wxInfoBar"), obj->GetPropertyAsString(_("name")));
        xrc.AddWindowProperties();
#else
        ObjectToXrcFilter xrc(obj, _("unknown"), obj->GetPropertyAsString(_("name")));
#endif
        return xrc.GetXrcObject();
    }
#if wxVERSION_NUMBER >= 3130
    ticpp::Element* ImportFromXrc(ticpp::Element* xrcObj) override
    {
        XrcToXfbFilter filter(xrcObj, _("wxInfoBar"));
        filter.AddWindowProperties();
        return filter.GetXfbObject();
    }
#endif
};

void ComponentEvtHandler::OnButton(wxCommandEvent& event)
{
    wxInfoBar* infoBar = wxDynamicCast(m_window, wxInfoBar);
    if (infoBar) {
        m_timer.SetOwner(this);
        m_timer.Start(infoBar->GetEffectDuration() + 1000, true);
    }
    event.Skip();
}

void ComponentEvtHandler::OnTimer(wxTimerEvent&)
{
    wxInfoBar* infoBar = wxDynamicCast(m_window, wxInfoBar);
    if (infoBar)
        infoBar->ShowMessage(_("Message ..."));
}

BEGIN_LIBRARY()
WINDOW_COMPONENT("wxButton", ButtonComponent)
WINDOW_COMPONENT("wxBitmapButton", BitmapButtonComponent)
WINDOW_COMPONENT("wxTextCtrl", TextCtrlComponent)
WINDOW_COMPONENT("wxStaticText", StaticTextComponent)
WINDOW_COMPONENT("wxComboBox", ComboBoxComponent)
WINDOW_COMPONENT("wxBitmapComboBox", BitmapComboBoxComponent)
WINDOW_COMPONENT("wxListBox", ListBoxComponent)
WINDOW_COMPONENT("wxRadioBox", RadioBoxComponent)
WINDOW_COMPONENT("wxRadioButton", RadioButtonComponent)
WINDOW_COMPONENT("wxCheckBox", CheckBoxComponent)
WINDOW_COMPONENT("wxStaticBitmap", StaticBitmapComponent)
WINDOW_COMPONENT("wxStaticLine", StaticLineComponent)
WINDOW_COMPONENT("wxMenuBar", MenuBarComponent)
ABSTRACT_COMPONENT("wxMenu", MenuComponent)
ABSTRACT_COMPONENT("submenu", SubMenuComponent)
ABSTRACT_COMPONENT("wxMenuItem", MenuItemComponent)
ABSTRACT_COMPONENT("separator", SeparatorComponent)
WINDOW_COMPONENT("wxListCtrl", ListCtrlComponent)
WINDOW_COMPONENT("wxStatusBar", StatusBarComponent)
WINDOW_COMPONENT("wxToolBar", ToolBarComponent)
WINDOW_COMPONENT("wxAuiToolBar", AuiToolBarComponent)
ABSTRACT_COMPONENT("tool", ToolComponent)
ABSTRACT_COMPONENT("toolSeparator", ToolSeparatorComponent)
WINDOW_COMPONENT("wxChoice", ChoiceComponent)
WINDOW_COMPONENT("wxSlider", SliderComponent)
WINDOW_COMPONENT("wxGauge", GaugeComponent)
WINDOW_COMPONENT("wxAnimationCtrl", AnimCtrlComponent)
WINDOW_COMPONENT("wxInfoBar", InfoBarComponent)

// wxButton
MACRO(wxBU_LEFT)
MACRO(wxBU_TOP)
MACRO(wxBU_RIGHT)
MACRO(wxBU_BOTTOM)
MACRO(wxBU_EXACTFIT)
MACRO(wxBU_NOTEXT)
MACRO(wxLEFT)
MACRO(wxRIGHT)
MACRO(wxTOP)
MACRO(wxBOTTOM)

// wxStaticText
MACRO(wxALIGN_LEFT)
MACRO(wxALIGN_CENTER_HORIZONTAL)
MACRO(wxALIGN_RIGHT)
MACRO(wxST_NO_AUTORESIZE)
MACRO(wxST_ELLIPSIZE_START)
MACRO(wxST_ELLIPSIZE_MIDDLE)
MACRO(wxST_ELLIPSIZE_END)

// wxTextCtrl
MACRO(wxTE_MULTILINE)
MACRO(wxTE_READONLY)
MACRO(wxTE_RICH)
MACRO(wxTE_AUTO_URL)
MACRO(wxTE_CAPITALIZE)
MACRO(wxTE_CENTER)
MACRO(wxTE_CHARWRAP)
MACRO(wxTE_DONTWRAP)
MACRO(wxTE_LEFT)
MACRO(wxTE_NOHIDESEL)
MACRO(wxTE_PASSWORD)
MACRO(wxTE_PROCESS_ENTER)
MACRO(wxTE_PROCESS_TAB)
MACRO(wxTE_RICH2)
MACRO(wxTE_RIGHT)
MACRO(wxTE_WORDWRAP)
MACRO(wxTE_BESTWRAP)
MACRO(wxTE_NO_VSCROLL)

// wxStaticLine
MACRO(wxLI_HORIZONTAL)
MACRO(wxLI_VERTICAL)

// wxListCtrl
MACRO(wxLC_LIST)
MACRO(wxLC_REPORT)
MACRO(wxLC_VIRTUAL)
MACRO(wxLC_ICON)
MACRO(wxLC_SMALL_ICON)
MACRO(wxLC_ALIGN_TOP)
MACRO(wxLC_ALIGN_LEFT)
MACRO(wxLC_AUTOARRANGE)
MACRO(wxLC_EDIT_LABELS)
MACRO(wxLC_NO_SORT_HEADER)
MACRO(wxLC_NO_HEADER)
MACRO(wxLC_SINGLE_SEL)
MACRO(wxLC_SORT_ASCENDING)
MACRO(wxLC_SORT_DESCENDING)
MACRO(wxLC_HRULES)
MACRO(wxLC_VRULES)

// wxListBox
MACRO(wxLB_SINGLE)
MACRO(wxLB_MULTIPLE)
MACRO(wxLB_EXTENDED)
MACRO(wxLB_HSCROLL)
MACRO(wxLB_ALWAYS_SB)
MACRO(wxLB_NEEDED_SB)
MACRO(wxLB_NO_SB)
MACRO(wxLB_SORT)

// wxRadioBox
MACRO(wxRA_SPECIFY_ROWS)
MACRO(wxRA_SPECIFY_COLS)

// wxRadioButton
MACRO(wxRB_GROUP)
MACRO(wxRB_SINGLE)

// wxStatusBar
MACRO(wxSTB_SIZEGRIP)
MACRO(wxSTB_SHOW_TIPS)
MACRO(wxSTB_ELLIPSIZE_START)
MACRO(wxSTB_ELLIPSIZE_MIDDLE)
MACRO(wxSTB_ELLIPSIZE_END)
MACRO(wxSTB_DEFAULT_STYLE)

// wxMenuItem & wxTool
MACRO(wxITEM_NORMAL)
MACRO(wxITEM_CHECK)
MACRO(wxITEM_RADIO)

// wxToolBar
MACRO(wxTB_FLAT)
MACRO(wxTB_DOCKABLE)
MACRO(wxTB_HORIZONTAL)
MACRO(wxTB_VERTICAL)
MACRO(wxTB_TEXT)
MACRO(wxTB_NOICONS)
MACRO(wxTB_NODIVIDER)
MACRO(wxTB_NOALIGN)
MACRO(wxTB_HORZ_LAYOUT)
MACRO(wxTB_HORZ_TEXT)
MACRO(wxTB_NO_TOOLTIPS)
MACRO(wxTB_BOTTOM)
MACRO(wxTB_RIGHT)
MACRO(wxTB_DEFAULT_STYLE)

// wxAuiToolBar
MACRO(wxAUI_TB_TEXT)
MACRO(wxAUI_TB_NO_TOOLTIPS)
MACRO(wxAUI_TB_NO_AUTORESIZE)
MACRO(wxAUI_TB_GRIPPER)
MACRO(wxAUI_TB_OVERFLOW)
MACRO(wxAUI_TB_VERTICAL)
MACRO(wxAUI_TB_HORZ_LAYOUT)
MACRO(wxAUI_TB_HORIZONTAL)
MACRO(wxAUI_TB_PLAIN_BACKGROUND)
MACRO(wxAUI_TB_HORZ_TEXT)
MACRO(wxAUI_TB_DEFAULT_STYLE)

// wxSlider
MACRO(wxSL_AUTOTICKS)
MACRO(wxSL_BOTTOM)
MACRO(wxSL_HORIZONTAL)
MACRO(wxSL_INVERSE)
MACRO(wxSL_MIN_MAX_LABELS)
MACRO(wxSL_VALUE_LABEL)
MACRO(wxSL_LABELS)
MACRO(wxSL_LEFT)
MACRO(wxSL_RIGHT)
MACRO(wxSL_SELRANGE)
MACRO(wxSL_TOP)
MACRO(wxSL_VERTICAL)
MACRO(wxSL_BOTH)

// wxComboBox
MACRO(wxCB_DROPDOWN)
MACRO(wxCB_READONLY)
MACRO(wxCB_SIMPLE)
MACRO(wxCB_SORT)

// wxCheckBox
MACRO(wxCHK_2STATE)
MACRO(wxCHK_3STATE)
MACRO(wxCHK_ALLOW_3RD_STATE_FOR_USER)

// wxGauge
MACRO(wxGA_HORIZONTAL)
MACRO(wxGA_SMOOTH)
MACRO(wxGA_VERTICAL)

// wxAnimationCtrl
MACRO(wxAC_DEFAULT_STYLE)
MACRO(wxAC_NO_AUTORESIZE)

// wxInfoBar
MACRO(wxSHOW_EFFECT_NONE)
MACRO(wxSHOW_EFFECT_ROLL_TO_LEFT)
MACRO(wxSHOW_EFFECT_ROLL_TO_RIGHT)
MACRO(wxSHOW_EFFECT_ROLL_TO_TOP)
MACRO(wxSHOW_EFFECT_ROLL_TO_BOTTOM)
MACRO(wxSHOW_EFFECT_SLIDE_TO_LEFT)
MACRO(wxSHOW_EFFECT_SLIDE_TO_RIGHT)
MACRO(wxSHOW_EFFECT_SLIDE_TO_TOP)
MACRO(wxSHOW_EFFECT_SLIDE_TO_BOTTOM)
MACRO(wxSHOW_EFFECT_BLEND)
MACRO(wxSHOW_EFFECT_EXPAND)
END_LIBRARY()
